---
- name: Install MariaDB Server
  ansible.builtin.apt:
    name: mariadb-server
    state: present
    update_cache: yes

- name: Start and enable MariaDB service
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: yes

# Catatan: Konfigurasi ini sangat dasar.
# Untuk produksi, diperlukan hardening, pembuatan user, dan database spesifik.
- name: Secure MariaDB (basic idempotency)
  ansible.builtin.command: mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ lookup('env', 'DB_ROOT_PASSWORD') }}'; FLUSH PRIVILEGES;"
  changed_when: false # Perintah ini tidak idempotent, jadi kita asumsikan tidak berubah

- name: Create the application database
  ansible.builtin.command: mysql -u root -p"{{ lookup('env', 'DB_ROOT_PASSWORD') }}" -e "CREATE DATABASE IF NOT EXISTS book_library;"
