---
# Playbook Utama untuk Arsitektur Full EC2

# Play 1: Setup Cluster Database
- name: Configure and Deploy MariaDB Galera Cluster
  hosts: database_servers
  become: yes
  roles:
    - role: ansible-mariadb-galera-cluster

# Play 2: Setup Server Aplikasi Backend
- name: Configure and Deploy Backend Servers
  hosts: backend_servers
  become: yes
  vars:
    # Arahkan backend ke IP pertama dari cluster database.
    # Untuk HA sejati, ini seharusnya DNS name dari sebuah Load Balancer database.
    db_host: "{{ hostvars[groups['database_servers'][0]]['ansible_host'] }}"
  roles:
    - role: backend

# Play 3: Setup Server Web Frontend
- name: Configure and Deploy Web Servers
  hosts: web_servers
  become: yes
  roles:
    - role: webserver # Menggunakan role baru/yang disederhanakan

# Play 4: Setup Nginx Load Balancer
- name: Configure and Deploy Nginx Load Balancer
  hosts: nginx_lb
  become: yes
  roles:
    - role: nginx-loadbalancer # Role baru untuk LB

# Play 5: Tampilkan Alamat IP Final
- name: Display Final Access IP
  hosts: localhost
  connection: local
  tasks:
    - name: Print the public IP of the Load Balancer
      ansible.builtin.debug:
        msg: "Aplikasi Anda sekarang dapat diakses melalui alamat IP Load Balancer: http://{{ hostvars[groups['nginx_lb'][0]]['ansible_host'] }}"